'use strict';
Object.defineProperty(exports, '__esModule', { value: true });
const express_1 = require('express');
require('..\\controllers\\gastos.controllers');
const gastos_controllers_1 = require('..\\controllers\\gastos.controllers');
const router = (0, express_1.Router)();
router.post('/createGastoDiario', gastos_controllers_1.createGastoDiario);
router.get('/getGastos', gastos_controllers_1.getGastos);
router.get('/getSemanas/:semana?', gastos_controllers_1.getSemanas);
router.get('/getDay/:day?', gastos_controllers_1.getDay);
router.post('/updateGasto', gastos_controllers_1.updateGasto);
exports.default = router;